-- Smart Inventory Supabase schema
-- Run this in Supabase SQL Editor before using the app.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  owner_name text not null default '',
  shop_name text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.inventory (
  id text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  purchase_price numeric not null default 0,
  selling_price numeric not null default 0,
  quantity integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, id)
);

create table if not exists public.activity (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null,
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.inventory enable row level security;
alter table public.activity enable row level security;

drop policy if exists "profiles own row" on public.profiles;
create policy "profiles own row" on public.profiles for all using (auth.uid() = id) with check (auth.uid() = id);
drop policy if exists "inventory own rows" on public.inventory;
create policy "inventory own rows" on public.inventory for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "activity own rows" on public.activity;
create policy "activity own rows" on public.activity for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
